// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'FIREBASE_WEB_API_KEY',
    appId: '1:52545957572:web:a83ddd26627607db20a391',
    messagingSenderId: '52545957572',
    projectId: 'gpizza-firebase',
    authDomain: 'gpizza-firebase.firebaseapp.com',
    storageBucket: 'gpizza-firebase.firebasestorage.app',
    measurementId: 'G-JJVCS1TV5J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'FIREBASE_ANDROID_API_KEY',
    appId: '1:52545957572:android:27e8d09d58c7cb1d20a391',
    messagingSenderId: '52545957572',
    projectId: 'gpizza-firebase',
    storageBucket: 'gpizza-firebase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'FIREBASE_IOS_API_KEY',
    appId: '1:52545957572:ios:c0cf7b6ab316684520a391',
    messagingSenderId: '52545957572',
    projectId: 'gpizza-firebase',
    storageBucket: 'gpizza-firebase.firebasestorage.app',
    iosBundleId: 'com.example.gpizza',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'FIREBASE_IOS_API_KEY',
    appId: '1:52545957572:ios:c0cf7b6ab316684520a391',
    messagingSenderId: '52545957572',
    projectId: 'gpizza-firebase',
    storageBucket: 'gpizza-firebase.firebasestorage.app',
    iosBundleId: 'com.example.gpizza',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'FIREBASE_WEB_API_KEY',
    appId: '1:52545957572:web:909507d22658d94920a391',
    messagingSenderId: '52545957572',
    projectId: 'gpizza-firebase',
    authDomain: 'gpizza-firebase.firebaseapp.com',
    storageBucket: 'gpizza-firebase.firebasestorage.app',
    measurementId: 'G-HL20RS40V1',
  );
}
